#ifndef SNAPSHOTPLUGIN_GLOBAL_H
#define SNAPSHOTPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SNAPSHOTPLUGIN_LIBRARY)
#  define SNAPSHOTPLUGIN_EXPORT Q_DECL_EXPORT
#else
#  define SNAPSHOTPLUGIN_EXPORT Q_DECL_IMPORT
#endif

#endif // SNAPSHOTPLUGIN_GLOBAL_H
